{% set name = "embiggen" %}
{% set version = "0.11.95" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/embiggen-{{ version }}.tar.gz
  sha256: 6e68b501be2e1ee80a2d2a799bd321dbb1d53c8bb2608118440c09bdc9acb864

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - jinja2
    - tqdm
    - humanize
    - matplotlib-base >=3.5.2
    - scikit-learn >=1.2
    - dict_hash >=1.1.32
    - userinput >=1.0.20
    - ddd_subplots >=1.0.27
    - sanitize_ml_labels >=1.0.50
    - keras_mixed_sequence >=1.0.28
    - ensmallen_graph >=0.8.94
    - environments_utils >=1.0.10
    - compress-pickle >=2.1.0
    - validate_version_code
    - cache_decorator >=2.1.14
    - threadpoolctl >=3.1.0
    - pydot
    - packaging

test:
  imports:
    - embiggen
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/monarch-initiative/embiggen
  summary: Embiggen is the Python Graph Representation learning, Prediction and Evaluation module processing submodule of the GRAPE library.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillonroach
    - isuruf
